sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
  - $HOME/.pip-cache
dist: trusty
language: python
env:
  TOX_PARALLEL_NO_SPINNER: 1


matrix:
  include:
    - python: '3.6'
      env: TOXENV="flake8,flake8-docs"

    - python: '3.6'
      env: TOXENV="py36-linux"

    - python: '3.7'
      env:
        - TOXENV="py37-linux"
        - BOTO_CONFIG="/dev/null"
      dist: xenial
      sudo: true
      
    - python: '3.8'
      env:
        - TOXENV="py38-linux"
      dist: bionic


install:
  - pip install tox

script: tox -vv
